# Generated by Django 5.2.4 on 2025-08-09 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grid_search', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={},
        ),
        migrations.RemoveField(
            model_name='data',
            name='description',
        ),
    ]
