# Generated by Django 5.2.5 on 2025-10-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid_search', '0002_alter_data_options_remove_data_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='nid',
            field=models.CharField(max_length=10),
        ),
    ]
