# Generated by Django 5.2.4 on 2025-08-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stage', models.CharField(max_length=100)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('days_left', models.IntegerField()),
                ('alert', models.BooleanField()),
            ],
        ),
    ]
