# Generated by Django 5.2.4 on 2025-08-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_type', models.CharField(max_length=50)),
                ('phone_numbers', models.CharField(max_length=100)),
                ('emails', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=100)),
                ('education_level', models.CharField(max_length=100)),
                ('socioeconomic_status', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city_of_residence', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('vital_status', models.CharField(max_length=10)),
                ('intake_date', models.DateField()),
                ('procedure_type', models.CharField(max_length=100)),
                ('request_status', models.CharField(max_length=100)),
                ('request_date', models.DateField()),
                ('appointment_date', models.DateField()),
                ('provider', models.CharField(max_length=150)),
                ('barrier', models.TextField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('timeliness', models.IntegerField()),
                ('care_pathway', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='board',
            name='start_date',
            field=models.DateField(),
        ),
    ]
