# Generated by Django 5.2.4 on 2025-08-05 17:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0002_medicalrequest_patient_alter_board_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='appointment_date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='barrier',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='care_pathway',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='intake_date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='month',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='procedure_type',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='request_date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='request_status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='timeliness',
        ),
        migrations.AddField(
            model_name='medicalrequest',
            name='appointment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='medicalrequest',
            name='barrier',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrequest',
            name='care_pathway',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalrequest',
            name='intake_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrequest',
            name='month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='medicalrequest',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrequest',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indicadores.patient'),
        ),
        migrations.AddField(
            model_name='medicalrequest',
            name='procedure_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalrequest',
            name='provider',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='medicalrequest',
            name='request_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrequest',
            name='request_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalrequest',
            name='timeliness',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrequest',
            name='case_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
