# Generated by Django 5.2.4 on 2025-08-15 15:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0003_remove_patient_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrequest',
            name='appointment_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Cita Programada 📅'),
        ),
        migrations.AlterField(
            model_name='medicalrequest',
            name='barrier',
            field=models.TextField(blank=True, null=True, verbose_name='Barreras Identificadas 🚧'),
        ),
        migrations.AlterField(
            model_name='medicalrequest',
            name='care_pathway',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ruta Asistencial 🗺️'),
        ),
        migrations.AlterField(
            model_name='medicalrequest',
            name='case_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Caso ⚙️'),
        ),
        migrations.AlterField(
            model_name='medicalrequest',
            name='intake_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Captación 📅'),
        ),
        migrations.AlterField(
            model_name='medicalrequest',
            name='month',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mes de Registro 🗓️'),
        ),
        migrations.AlterField(
            model_name='medicalrequest',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones Relevantes 📝'),
        ),
        migrations.AlterField(
            model_name='medicalrequest',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indicadores.patient', verbose_name='Paciente 🧍'),
        ),
        migrations.AlterField(
            model_name='medicalrequest',
            name='procedure_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Procedimiento ⏳'),
        ),
        migrations.AlterField(
            model_name='medicalrequest',
            name='provider',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Prestador del Servicio 🏢'),
        ),
        migrations.AlterField(
            model_name='medicalrequest',
            name='request_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Solicitud 📅'),
        ),
        migrations.AlterField(
            model_name='medicalrequest',
            name='request_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado de la Solicitud 📌'),
        ),
        migrations.AlterField(
            model_name='medicalrequest',
            name='timeliness',
            field=models.IntegerField(blank=True, null=True, verbose_name='Oportunidad (días) ⏱️'),
        ),
    ]
