# Generated by Django 5.2.5 on 2025-10-22 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0004_alter_medicalrequest_appointment_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='board',
        ),
        migrations.DeleteModel(
            name='MedicalRequest',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
